/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_attribute_key = 1,
  aux_sym_section_name_header_token1 = 2,
  anon_sym_COLON = 3,
  sym_section_name = 4,
  anon_sym_SPACE = 5,
  aux_sym_section_name_continuation_token1 = 6,
  sym_manifest = 7,
  sym_main_section = 8,
  sym_individual_section = 9,
  sym_section_name_header = 10,
  sym_section_name_continuation = 11,
  sym_header_value = 12,
  sym_attribute_entry = 13,
  sym_continuation_line = 14,
  sym_continuation_value = 15,
  aux_sym_manifest_repeat1 = 16,
  aux_sym_main_section_repeat1 = 17,
  aux_sym_individual_section_repeat1 = 18,
  aux_sym_section_name_header_repeat1 = 19,
  aux_sym_header_value_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_attribute_key] = "attribute_key",
  [aux_sym_section_name_header_token1] = "section_name_header_token1",
  [anon_sym_COLON] = ": ",
  [sym_section_name] = "section_name",
  [anon_sym_SPACE] = " ",
  [aux_sym_section_name_continuation_token1] = "section_name_continuation_token1",
  [sym_manifest] = "manifest",
  [sym_main_section] = "main_section",
  [sym_individual_section] = "individual_section",
  [sym_section_name_header] = "section_name_header",
  [sym_section_name_continuation] = "section_name_continuation",
  [sym_header_value] = "header_value",
  [sym_attribute_entry] = "attribute_entry",
  [sym_continuation_line] = "continuation_line",
  [sym_continuation_value] = "continuation_value",
  [aux_sym_manifest_repeat1] = "manifest_repeat1",
  [aux_sym_main_section_repeat1] = "main_section_repeat1",
  [aux_sym_individual_section_repeat1] = "individual_section_repeat1",
  [aux_sym_section_name_header_repeat1] = "section_name_header_repeat1",
  [aux_sym_header_value_repeat1] = "header_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_attribute_key] = sym_attribute_key,
  [aux_sym_section_name_header_token1] = aux_sym_section_name_header_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_section_name] = sym_section_name,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_section_name_continuation_token1] = aux_sym_section_name_continuation_token1,
  [sym_manifest] = sym_manifest,
  [sym_main_section] = sym_main_section,
  [sym_individual_section] = sym_individual_section,
  [sym_section_name_header] = sym_section_name_header,
  [sym_section_name_continuation] = sym_section_name_continuation,
  [sym_header_value] = sym_header_value,
  [sym_attribute_entry] = sym_attribute_entry,
  [sym_continuation_line] = sym_continuation_line,
  [sym_continuation_value] = sym_continuation_value,
  [aux_sym_manifest_repeat1] = aux_sym_manifest_repeat1,
  [aux_sym_main_section_repeat1] = aux_sym_main_section_repeat1,
  [aux_sym_individual_section_repeat1] = aux_sym_individual_section_repeat1,
  [aux_sym_section_name_header_repeat1] = aux_sym_section_name_header_repeat1,
  [aux_sym_header_value_repeat1] = aux_sym_header_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_section_name_header_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_name_continuation_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_manifest] = {
    .visible = true,
    .named = true,
  },
  [sym_main_section] = {
    .visible = true,
    .named = true,
  },
  [sym_individual_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name_header] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation_line] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_manifest_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_main_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_individual_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_name_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 18,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(6);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\f') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_section_name_continuation_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_attribute_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(0);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_section_name_header_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_attribute_key] = ACTIONS(1),
    [aux_sym_section_name_header_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_manifest] = STATE(27),
    [sym_main_section] = STATE(7),
    [sym_attribute_entry] = STATE(2),
    [sym_continuation_line] = STATE(2),
    [aux_sym_main_section_repeat1] = STATE(2),
    [sym_attribute_key] = ACTIONS(3),
    [anon_sym_SPACE] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_attribute_key,
    ACTIONS(5), 1,
      anon_sym_SPACE,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      aux_sym_section_name_header_token1,
    STATE(3), 3,
      sym_attribute_entry,
      sym_continuation_line,
      aux_sym_main_section_repeat1,
  [18] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_attribute_key,
    ACTIONS(16), 1,
      aux_sym_section_name_header_token1,
    ACTIONS(18), 1,
      anon_sym_SPACE,
    STATE(3), 3,
      sym_attribute_entry,
      sym_continuation_line,
      aux_sym_main_section_repeat1,
  [36] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_SPACE,
    ACTIONS(23), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
    STATE(4), 2,
      sym_section_name_continuation,
      aux_sym_section_name_header_repeat1,
  [51] = 4,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      anon_sym_SPACE,
    ACTIONS(30), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
    STATE(4), 2,
      sym_section_name_continuation,
      aux_sym_section_name_header_repeat1,
  [66] = 4,
    ACTIONS(32), 1,
      anon_sym_SPACE,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
    STATE(5), 2,
      sym_section_name_continuation,
      aux_sym_section_name_header_repeat1,
  [81] = 4,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      aux_sym_section_name_header_token1,
    STATE(8), 1,
      sym_section_name_header,
    STATE(9), 2,
      sym_individual_section,
      aux_sym_manifest_repeat1,
  [95] = 4,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      sym_attribute_key,
    ACTIONS(46), 1,
      aux_sym_section_name_header_token1,
    STATE(14), 2,
      sym_attribute_entry,
      aux_sym_individual_section_repeat1,
  [109] = 4,
    ACTIONS(40), 1,
      aux_sym_section_name_header_token1,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_section_name_header,
    STATE(13), 2,
      sym_individual_section,
      aux_sym_manifest_repeat1,
  [123] = 4,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_SPACE,
    STATE(12), 1,
      aux_sym_header_value_repeat1,
    ACTIONS(52), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [137] = 4,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      sym_attribute_key,
    ACTIONS(61), 1,
      aux_sym_section_name_header_token1,
    STATE(11), 2,
      sym_attribute_entry,
      aux_sym_individual_section_repeat1,
  [151] = 4,
    ACTIONS(54), 1,
      anon_sym_SPACE,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_header_value_repeat1,
    ACTIONS(65), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [165] = 4,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      aux_sym_section_name_header_token1,
    STATE(8), 1,
      sym_section_name_header,
    STATE(13), 2,
      sym_individual_section,
      aux_sym_manifest_repeat1,
  [179] = 4,
    ACTIONS(44), 1,
      sym_attribute_key,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      aux_sym_section_name_header_token1,
    STATE(11), 2,
      sym_attribute_entry,
      aux_sym_individual_section_repeat1,
  [193] = 4,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      anon_sym_SPACE,
    STATE(15), 1,
      aux_sym_header_value_repeat1,
    ACTIONS(78), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [207] = 2,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(85), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [216] = 2,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(89), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [225] = 2,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(93), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [234] = 2,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(97), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [243] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(78), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [252] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 2,
      aux_sym_section_name_header_token1,
      sym_attribute_key,
  [260] = 2,
    ACTIONS(99), 1,
      aux_sym_section_name_continuation_token1,
    STATE(16), 1,
      sym_continuation_value,
  [267] = 2,
    ACTIONS(101), 1,
      aux_sym_section_name_continuation_token1,
    STATE(18), 1,
      sym_header_value,
  [274] = 2,
    ACTIONS(101), 1,
      aux_sym_section_name_continuation_token1,
    STATE(21), 1,
      sym_header_value,
  [281] = 1,
    ACTIONS(103), 1,
      anon_sym_COLON,
  [285] = 1,
    ACTIONS(105), 1,
      anon_sym_COLON,
  [289] = 1,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
  [293] = 1,
    ACTIONS(109), 1,
      aux_sym_section_name_continuation_token1,
  [297] = 1,
    ACTIONS(111), 1,
      aux_sym_section_name_continuation_token1,
  [301] = 1,
    ACTIONS(113), 1,
      sym_section_name,
  [305] = 1,
    ACTIONS(115), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 81,
  [SMALL_STATE(8)] = 95,
  [SMALL_STATE(9)] = 109,
  [SMALL_STATE(10)] = 123,
  [SMALL_STATE(11)] = 137,
  [SMALL_STATE(12)] = 151,
  [SMALL_STATE(13)] = 165,
  [SMALL_STATE(14)] = 179,
  [SMALL_STATE(15)] = 193,
  [SMALL_STATE(16)] = 207,
  [SMALL_STATE(17)] = 216,
  [SMALL_STATE(18)] = 225,
  [SMALL_STATE(19)] = 234,
  [SMALL_STATE(20)] = 243,
  [SMALL_STATE(21)] = 252,
  [SMALL_STATE(22)] = 260,
  [SMALL_STATE(23)] = 267,
  [SMALL_STATE(24)] = 274,
  [SMALL_STATE(25)] = 281,
  [SMALL_STATE(26)] = 285,
  [SMALL_STATE(27)] = 289,
  [SMALL_STATE(28)] = 293,
  [SMALL_STATE(29)] = 297,
  [SMALL_STATE(30)] = 301,
  [SMALL_STATE(31)] = 305,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main_section, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_main_section, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_main_section_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_main_section_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [16] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_main_section_repeat1, 2, 0, 0),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_main_section_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_name_header_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_name_header_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_name_header_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name_header, 4, 0, 3),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_name_header, 4, 0, 3),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name_header, 3, 0, 3),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_name_header, 3, 0, 3),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manifest, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_individual_section, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_individual_section, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manifest, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_value, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_value, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_individual_section_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_individual_section_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_individual_section_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_value, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_value, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_individual_section, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_individual_section, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation_line, 2, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continuation_line, 2, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation_value, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continuation_value, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_entry, 3, 0, 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_entry, 3, 0, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name_continuation, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_name_continuation, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [107] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_java_manifest(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_attribute_key,
    .primary_state_ids = ts_primary_state_ids,
    .name = "java_manifest",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 5,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
